# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w8XhHuQBYl5gnHIg40zxkiUJ3WYnHaci
"""

x_o=2
eta=0.01
eps=0.000001
del_x=1
max_iters=10000
iters=0
y,z=0,0
def deriv(x):
  y=x**3
  x_deriv=4*(y)+6*(x)
  
  return x_deriv
while abs(del_x)>eps and iters<max_iters:
  prev_x=x_o
  del_x=-eta*deriv(prev_x)
  x_o=x_o+del_x
  iters=iters+1

print("Minimum occurs at",x_o)